language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer update $COMPOSER_OPTIONS
